github.com:
    users:
        "7567491":
            oauth_token: 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
    oauth_token: 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
    user: "7567491"
